#!/bin/bash
# THIS SCRIPT MUST BE PLACED IN $PATH TO WORK CORRECTLY.

get_conky_list() {
    local conkyfile=$1
    # Get currently running conkys
    ps aux | grep -i '[c]onky -c' | awk '{ for(i=1;i<=NF;i++){ if($i ~ /\.conf$/ && system("[ -f \""$i"\" ]") == 0) print $i } }' | sort -u > "$conkyfile"
    # Add prefix
    sed -i -e 's|^|conky -c |' "$conkyfile"
    # Add shebang
    sed -i '1i #!/bin/bash' "$conkyfile"
    chmod 755 "$conkyfile"
}

update_transparency() {
    local conf_path=$1
    if pgrep -x picom > /dev/null 2>&1; then
        sed -i '/own_window_transparent/c\own_window_transparent = true,' "$conf_path"
        sed -i '/own_window_argb_visual/c\own_window_argb_visual = true,' "$conf_path"
        sed -i '/own_window_argb_value/c\own_window_argb_value = 0,' "$conf_path"
    else
        sed -i '/own_window_transparent/c\own_window_transparent = true,' "$conf_path"
        sed -i '/own_window_argb_visual/c\-- own_window_argb_visual = true,' "$conf_path"
        sed -i '/own_window_argb_value/c\-- own_window_argb_value = 0,' "$conf_path"
    fi
}

# Openbox or Awesome
if pgrep "awesome" > /dev/null; then
    conkyfile="$HOME/.config/awesome/conky-awesome/scripts/conky-restart-list"
    conkydir="$HOME/.config/awesome/conky-awesome"
else
    conkyfile="$HOME/.config/conky/scripts/conky-restart-list"
    conkydir="$HOME/.config/conky"
fi

# Make the list
get_conky_list "$conkyfile"

# Kill all running conkys
killall conky 2>/dev/null

# Add transparency
while IFS= read -r line; do
    conf=$(echo "$line" | awk '{print $3}')
    update_transparency "$conf"
done < <(tail -n +2 "$conkyfile")  # Skip shebang

# Restart conkys one by one
tail -n +2 "$conkyfile" | while IFS= read -r line; do
    eval "$line" &
    sleep 0.3
done

exit 0
